name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main", "ft/chatbot-codebase" ]

# env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: docker.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: samanja-dev
          IMAGE_TAG: latest
        run: |
          docker build -t samanja-dev .
          docker tag samanja-dev:latest public.ecr.aws/t5i1x5v9/samanja-dev:latest
          docker push public.ecr.aws/t5i1x5v9/samanja-dev:latest

        # - uses: mr-smithers-excellent/docker-build-push@v6
        #   with:
        #     image: olawaleoyg/chatbot
        #     registry: docker.io
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}
            