name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main", "ft/chatbot-codebase" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: olawaleoyg/chatbot
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Test build and push to ECR
      #   id: ecr-test-build-and-push
      #   uses: aws-actions/amazon-ecr-build-and-push-image@v1
      #   with:
      #     repository-name: ${{ env.IMAGE_NAME }}
      #     image-tag: latest
      #     region: eu-west-2
      #     env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: eu-west-2 
      #     ECR_URI: ${{ secrets.ECR_URI }}
      #     TAG: latest
      #     CI_COMMIT_SHORT_SHA: ${{ github.sha }}
      # - run: |
      #     echo $ECR_URI
      #     echo $TAG
      #     echo $CI_COMMIT_SHORT_SHA
      #     aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      #     docker build -t $ECR_URI:$TAG -f ./apps/auth-service/Dockerfile .
      #     docker build -t $ECR_URI:$CI_COMMIT_SHORT_SHA -f ./apps/auth-service/Dockerfile .
      #     docker push $ECR_URI:$TAG
      #     docker push $ECR_URI:$CI_COMMIT_SHORT_SHA