name: Run Unit Tests
on:
  push:
    branches:
      - main
      # - ft/chatbot-codebase
  pull_request:
    branches:
      - main
      # - ft/chatbot-codebase

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Vitest Suite
      run: npm test
